version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      dependencies:
        patterns:
          - "*"
    labels:
      - "ci"
    schedule:
      interval: "monthly"
