#!/bin/bash
set -euo pipefail

. "$HOME"/repos/.venvs/jjmc89-bot-scripts/bin/activate

python3 "$HOME"/repos/jjmc89-bot-scripts/enwiki/category_double_redirect_fixer.py \
    -ns:14 \
    -transcludes:'Category redirect' \
    --always
