#!/bin/bash
set -euo pipefail

. "$HOME"/repos/.venvs/jjmc89-bot-scripts/bin/activate

python3 "$HOME"/repos/jjmc89-bot-scripts/enwiki/cfdw.py \
    -dir:"$HOME"/.pywikibot-cfdwl \
    -page:WP:Categories_for_discussion/Working/Large
