#!/bin/bash
# shellcheck disable=SC2086
set -euo pipefail

. "$HOME"/repos/.venvs/jjmc89-bot-scripts/bin/activate

python3 "$HOME"/repos/jjmc89-bot-scripts/multi/commons_potd_importer.py --always \
    -page:'User:JJMC89 bot/Commons picture of the day' \
    -page:'eu:User:JJMC89 bot/Commons eguneko irudia'
