#!/bin/bash
set -euo pipefail

. "$HOME"/repos/.venvs/jjmc89-bot-scripts/bin/activate

python3 "$HOME"/repos/jjmc89-bot-scripts/multi/commons_potd_importer.py \
    -page:'User:JJMC89 bot/Commons picture of the day' \
    -always
