#!/bin/bash
set -euo pipefail

. "$HOME"/repos/.venvs/jjmc89-bot-scripts/bin/activate

python3 "$HOME"/repos/jjmc89-bot-scripts/enwiki/draftification_tagger.py \
    -dir:"$HOME"/.pywikibot-dfy-tagger \
    --always \
    --start "$(date -ud '-15 min' +"%Y-%m-%dT%H:%M:%SZ")"
