#!/bin/bash
set -euo pipefail

. "$HOME"/repos/.venvs/jjmc89-bot-scripts/bin/activate

python3 "$HOME"/repos/jjmc89-bot-scripts/enwiki/draftification_report.py \
    'User:JJMC89 bot/report/Draftifications/weekly' \
    --start "$(date -ud "-1 week" +"%Y-%m-%dT00:00:00Z")" \
    --end "$(date -u +"%Y-%m-%dT00:00:00Z")"
