#!/bin/bash
set -euo pipefail

. "$HOME"/repos/.venvs/jjmc89-bot-scripts/bin/activate

python3 "$HOME"/repos/jjmc89-bot-scripts/enwiki/massmessage_list_updater.py \
    --always \
    --meta \
    --rename \
    'User:JJMC89 bot/config/UserGroupsMassMessageListUpdater'
