#!/bin/bash
set -euo pipefail

. "$HOME"/repos/.venvs/jjmc89-bot-scripts/bin/activate

python3 "$HOME"/repos/jjmc89-bot-scripts/multi/magic_links_replacer.py \
    -dir:"$HOME"/.pywikibot-mlb \
    -lang:hu \
    -ns:0,6,10,12,14,100 \
    -config:'User:Magic links bot/config/MagicLinksReplacer' \
    -cat:'Mágikus PMID-linkeket használó lapok' \
    -cat:'Mágikus ISBN-linkeket használó lapok' \
    -cat:'Mágikus RFC-linkeket használó lapok' \
    -always
