#!/bin/bash
set -euo pipefail

. "$HOME"/repos/.venvs/pwb/bin/activate

python3 "$HOME"/repos/pywikibot/scripts/touch.py \
    -purge -forcelinkupdate \
    -pt:1 \
    -page:'Wikipedia:Copyright problems' \
    -page:'Wikipedia:Picture of the day/On the main pages' \
    -cat:'Stub message templates needing attention' \
    -cat:'Non-free files with orphaned versions' \
    -cat:'Pending AfC submissions'
