#!/bin/bash
set -euo pipefail

. "$HOME"/repos/.venvs/pwb/bin/activate

python3 "$HOME"/repos/pywikibot/scripts/touch.py \
    -purge -forcelinkupdate \
    -pt:1 \
    -cat:'Pages using duplicate arguments in template calls'
