#!/bin/bash
set -euo pipefail

. "$HOME"/repos/.venvs/pwb/bin/activate

python3 "$HOME"/repos/pywikibot/scripts/touch.py \
    -purge -forcelinkupdate \
    -ns:0 \
    -cat:'Pages with script errors'
