#!/bin/bash
set -euo pipefail

. "$HOME"/repos/.venvs/pwb/bin/activate

python3 "$HOME"/repos/pywikibot/scripts/touch.py \
    -purge -forcelinkupdate \
    -cat:'Declined AfC submissions' \
    -cat:'Rejected AfC submissions'
