#!/bin/bash
set -euo pipefail

. "$HOME"/repos/.venvs/jjmc89-bot-scripts/bin/activate

python3 "$HOME"/repos/jjmc89-bot-scripts/multi/purge.py \
    --forcelinkupdate \
    -cat:'Declined AfC submissions' \
    -cat:'Rejected AfC submissions'
